spring:
  mail:
    host: smtp.gmail.com
    username: zulfiqarali.bscssef20@iba-suk.edu.pk
    password: nvdrrnyhjjzoessz
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true


